name: Canary Deployment

on:
  workflow_call

jobs:
  create_vm_up_compose:
    runs-on: ubuntu-latest
    env:
      RessourceGroupName: "micsi24sortitoutseul"
      RessourceGroupLocation: "francecentral"

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: true

      - name: Azure CLI Create Ressource Group
        uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{env.RessourceGroupName}} --location ${{env.RessourceGroupLocation}}
            echo "Azure ressource group created"

      - name: Azure ARM Deploy
        uses: azure/arm-deploy@v2
        with:
          ressourceGroupName: ${{env.RessourceGroupName}}
          template: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json
          parameters: adminUserName=${{secrets.AZURE_VM_LOGIN}} adminPasswordOrKey=${{secrets.AZURE_VM_PASSWORD}} vmName="Canary" vmSize="Standard_B2s"

      - name: Get Public IP @
        if: success()
        uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az vm show -d -g ${{env.RessourceGroupName}} -n Canary --query publicIps -o tsv
            echo "Azure_VM_IP=$(az vm show -d -g ${{env.RessourceGroupName}} -n Canary --query publicIps -o tsv)" >> $GITHUB_ENV

      - name: Install Docker on VM
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          script:
            curl -o install_docker.sh https://raw.githubusercontent.com/azure-custom-cli/scripts/refs/heads/main/install_docker_ubuntu.sh
            ls -al
            bash ./install_docker.sh

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}}

          source: "./docker-compose.yml"
          target: "."

      - name: Start compose file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
        